### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by fmarco76** [indigo-dc/orchent#1]
Hi Baz,

when I try to compile the cli I get an error:

```
building orchent ... # command-line-arguments
src/orchent/orchent.go:207: undefined: os.LookupEnv
src/orchent/orchent.go:404: undefined: os.LookupEnv
done
```

I think a dependency is missed but since this is my first run in go I have no idea how to fix it.

Cheers,
Marco

**Comment by bwegh** [comment]
Hi Marco, 

which version of go do you use?

**Comment by bwegh** [comment]
that method has been added in May 2015 to go:
https://github.com/golang/go/commit/e8c0d0f2f3d1e7b1ccc8f057cff24a490b2dc2a7#diff-b30ffd1cf7612ccebac97fced83d5106

so Version go1.5 or newer should work

**Comment by fmarco76** [comment]
yes, I am using the version packaged with debian stable and it is 1.3.3 so this is the problem.
Maybe you can add the minimum version in the readme or a check in the script.

Cheers!

**Comment by bwegh** [comment]
added to the readme
