### ISSUE TITLE
Orchent on DOCKER with SSL Orchestrator

### ISSUE THREAD

**Issue by gmolto** [indigo-dc/orchent#10]
Hi,

Since the PaaS Orchestrator is transitioning from HTTP to HTTPS I have tried to use Orchent against the HTTPS endpoint (https://orchestrator01-indigo.cloud.ba.infn.it/orchestrator/deployments) but I get the following error:

retrieving deployment list:
error requesting list of providers:
 Get https://orchestrator01-indigo.cloud.ba.infn.it/orchestrator/deployments: x509: failed to load system roots and no roots provided

Can Orchent be updated to support this feature (before the Orchestrator team decommissions  the non-SSL endpoint? /cc @alberto-brigandi 

Way to reproduce this problem:

alias orchent='docker run --rm -e ORCHENT_TOKEN=$ORCHENT_TOKEN -v $PWD:/data marica/orchent:latest --url=https://orchestrator01-indigo.cloud.ba.infn.it/orchestrator'
orchent depls

Expected behaviour:

Obtain the list of deployments.

**Comment by bwegh** [comment]
Hello,
thanks for reporting this, I need a bit more information as this is a typical 'it works for me' issue ;)

My result using orchent 0.3.1
```
$ uname -a
Linux 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux
$  export ORCHENT_URL=https://orchestrator01-indigo.cloud.ba.infn.it/orchestrator/
$ export ORCHENT_TOKEN=<an opaque string>
$ orchent depls
[ ...]
Deployment [cfcadb4c-2e6f-4adf-8867-00f3ee56f819]:
  status: CREATE_IN_PROGRESS
  creation time: 2016-10-19T13:42+0000
  update time: 2016-10-19T13:59+0000
  callback: 
Deployment [e8ec521a-092a-4652-b8eb-8be97acfdc62]:
  status: CREATE_IN_PROGRESS
  creation time: 2016-10-19T13:41+0000
  update time: 2016-10-19T13:41+0000
  callback: 
Deployment [bab40863-9bd3-414d-9ee3-a6701ab95f00]:
  status: CREATE_IN_PROGRESS
  creation time: 2016-10-19T13:41+0000
  update time: 2016-10-19T13:41+0000
  callback: 
Deployment [916d892e-db47-4ded-9ed6-433ef9259189]:
  status: CREATE_IN_PROGRESS
  creation time: 2016-10-19T13:41+0000
  update time: 2016-10-19T13:41+0000
  callback: 
Deployment [49a55f03-993c-4770-9b1f-feeb854612eb]:
  status: CREATE_COMPLETE
  creation time: 2016-10-19T13:41+0000
  update time: 2016-10-19T14:33+0000
  callback: 
Deployment [16defd7b-6bc9-4bb1-82ca-69caae3a7f28]:
  status: CREATE_IN_PROGRESS
  creation time: 2016-10-19T13:41+0000
  update time: 2016-10-19T13:41+0000
  callback: 
Deployment [f5327265-065f-477b-91a7-a151b4b47f7f]:
  status: CREATE_IN_PROGRESS
  creation time: 2016-10-19T13:41+0000
  update time: 2016-10-19T13:41+0000
  callback: 
Deployment [4fd154ce-2e62-47e8-90da-92ed5f9655ef]:
  status: CREATE_COMPLETE
  creation time: 2016-10-19T13:40+0000
  update time: 2016-10-19T14:57+0000
  callback: 
Deployment [2bd97c13-3260-4c33-9604-b469d7a5976d]:
  status: CREATE_IN_PROGRESS
  creation time: 2016-10-19T13:40+0000
  update time: 2016-10-19T13:41+0000
  callback: 
Deployment [5f0cdeec-5cab-485c-879d-f9f88bad5c30]:
  status: CREATE_COMPLETE
  creation time: 2016-10-19T13:33+0000
  update time: 2016-10-19T13:37+0000
  callback: 

  page: 23/39 [ #Elements: 390, size: 10 ]
  links:
    first [https://orchestrator01-indigo.cloud.ba.infn.it/orchestrator/deployments?page=0&size=10&sort=created,desc]
    prev [https://orchestrator01-indigo.cloud.ba.infn.it/orchestrator/deployments?page=22&size=10&sort=created,desc]
    self [https://orchestrator01-indigo.cloud.ba.infn.it/orchestrator/deployments]
    next [https://orchestrator01-indigo.cloud.ba.infn.it/orchestrator/deployments?page=24&size=10&sort=created,desc]
    last [https://orchestrator01-indigo.cloud.ba.infn.it/orchestrator/deployments?page=38&size=10&sort=created,desc]
[...]
```

**Comment by bwegh** [comment]
please first test it outside of the docker, if that also works for you it might be related to the docker image

**Comment by gmolto** [comment]
Thank you.

Unfortunately, I could not compile it on macOS 10.12.3. That is why I was using the Docker container.

The compilation fails producing this trace:

sh utils/compile.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]

running the build with 'go version go1.6 darwin/amd64', please include in issue reports

fetiching:
-n   kingpin ...
# gopkg.in/alecthomas/kingpin.v2
failed MSpanList_Insert 0xe3c1f0 0x456add4a5ac2 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x46e5c0, 0x10)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x90
runtime.(*mSpanList).insert(0x983d48, 0xe3c1f0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:933 +0x293
runtime.(*mheap).freeSpanLocked(0x983540, 0xe3c1f0, 0x100, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:809 +0x4be
runtime.(*mheap).grow(0x983540, 0x8, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:675 +0x2a0
runtime.(*mheap).allocSpanLocked(0x983540, 0x1, 0xe3c178)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:553 +0x4e3
runtime.(*mheap).alloc_m(0x983540, 0x1, 0x6, 0xe3c178)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:437 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc82045be58)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x983540, 0x1, 0x10000000006, 0xeb4f)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x984ab0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x984ab0, 0xe3c178)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0xaf5e10, 0x6, 0xe3c178)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc820022000)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:245 fp=0xc823431988 sp=0xc823431980
runtime.mallocgc(0x50, 0x428980, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/malloc.go:643 +0x869 fp=0xc823431a60 sp=0xc823431988
runtime.newobject(0x428980, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/malloc.go:781 +0x42 fp=0xc823431a88 sp=0xc823431a60
cmd/compile/internal/gc.ggloblsym(0xc823ee5380, 0xa00000030)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/gsubr.go:237 +0xe8 fp=0xc823431b78 sp=0xc823431a88
cmd/compile/internal/gc.stringsym(0xc823ef2960, 0x2a, 0x50, 0x428980)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/obj.go:238 +0x513 fp=0xc823431cd0 sp=0xc823431b78
cmd/compile/internal/gc.datagostring(0xc823ef2960, 0x2a, 0xc823ef94a8)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/obj.go:284 +0x3d fp=0xc823431dd0 sp=0xc823431cd0
cmd/compile/internal/gc.dgostrlitptr(0xc823ee5200, 0x28, 0xc823431ef8, 0x12)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/obj.go:313 +0x193 fp=0xc823431ec0 sp=0xc823431dd0
cmd/compile/internal/gc.dgostringptr(0xc823ee5200, 0x28, 0xc823ef2960, 0x2a, 0x28)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/obj.go:297 +0x66 fp=0xc823431ee8 sp=0xc823431ec0
cmd/compile/internal/gc.dcommontype(0xc823ee5200, 0x28, 0xc823ce7ef0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/reflect.go:772 +0x77f fp=0xc823432060 sp=0xc823431ee8
cmd/compile/internal/gc.dtypesym(0xc823ce7ef0, 0xc823ee4f00)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/reflect.go:1058 +0x671 fp=0xc823432200 sp=0xc823432060
cmd/compile/internal/gc.dextratype(0xc821725b00, 0x48, 0xc8211813b0, 0x30, 0x48)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/reflect.go:490 +0x11b fp=0xc823432298 sp=0xc823432200
cmd/compile/internal/gc.dtypesym(0xc8211813b0, 0xc821725880)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/reflect.go:1197 +0x35f fp=0xc823432438 sp=0xc823432298
cmd/compile/internal/gc.dtypesym(0xc8211814a0, 0xc821706880)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/reflect.go:1113 +0x11c1 fp=0xc8234325d8 sp=0xc823432438
cmd/compile/internal/gc.dtypesym(0xc8211885a0, 0xc821725980)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/reflect.go:1163 +0xcce fp=0xc823432778 sp=0xc8234325d8
cmd/compile/internal/gc.dtypesym(0xc821181b30, 0xc820f9e800)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/reflect.go:1151 +0x48f fp=0xc823432918 sp=0xc823432778
cmd/compile/internal/gc.dtypesym(0xc8211882d0, 0xc820de2180)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/reflect.go:1163 +0xcce fp=0xc823432ab8 sp=0xc823432918
cmd/compile/internal/gc.dtypesym(0xc821188000, 0xc8215c8580)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/reflect.go:1163 +0xcce fp=0xc823432c58 sp=0xc823432ab8
cmd/compile/internal/gc.dtypesym(0xc821186e10, 0xc821a4ff00)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/reflect.go:1151 +0x48f fp=0xc823432df8 sp=0xc823432c58
cmd/compile/internal/gc.dtypesym(0xc820ce3d10, 0xc8216b1400)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/reflect.go:1163 +0xcce fp=0xc823432f98 sp=0xc823432df8
cmd/compile/internal/gc.dtypesym(0xc82118aa50, 0xc820ce3b30)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/reflect.go:1151 +0x48f fp=0xc823433138 sp=0xc823432f98
cmd/compile/internal/gc.dtypesym(0xc820ce3680, 0xc821683880)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/reflect.go:1051 +0x5e7 fp=0xc8234332d8 sp=0xc823433138
cmd/compile/internal/gc.dtypesym(0xc821189860, 0xc823395f00)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/reflect.go:1028 +0xc0c fp=0xc823433478 sp=0xc8234332d8
cmd/compile/internal/gc.dtypesym(0xc821189590, 0xc821683600)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/reflect.go:1163 +0xcce fp=0xc823433618 sp=0xc823433478
cmd/compile/internal/gc.dtypesym(0xc82118cf00, 0xc821172090)
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/reflect.go:1151 +0x48f fp=0xc8234337b8 sp=0xc823433618
cmd/compile/internal/gc.dumptypestructs()
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/reflect.go:1250 +0x4c8 fp=0xc823433878 sp=0xc8234337b8
cmd/compile/internal/gc.dumpobj()
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/obj.go:76 +0xd58 fp=0xc823433ab0 sp=0xc823433878
cmd/compile/internal/gc.Main()
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/gc/lex.go:495 +0x2225 fp=0xc823433dd0 sp=0xc823433ab0
cmd/compile/internal/amd64.Main()
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/internal/amd64/galign.go:127 +0x58d fp=0xc823433e38 sp=0xc823433dd0
main.main()
	/usr/local/Cellar/go/1.6/libexec/src/cmd/compile/main.go:32 +0x395 fp=0xc823433f10 sp=0xc823433e38
runtime.main()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc823433f60 sp=0xc823433f10
runtime.goexit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc823433f68 sp=0xc823433f60
done
-n   sling ...
done
-n building orchent ...

**Comment by bwegh** [comment]
okay, can you in this case please add a link to the dockerfile?
So I can have a look at it

**Comment by gmolto** [comment]
The Docker image was created by @maricaantonacci  from scratch out of the statically-linked executable file. I do not have the Dockerfile.

**Comment by bwegh** [comment]
@maricaantonacci could you please add a link to the Dockerfile or a description on how to create it

**Comment by maricaantonacci** [comment]
I generated the statically-linked executable modifying the build instruction as follows:
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix -v ${GOPATH}/src/orchent/orchent.go

Then I used the following Dockerfile to create the image:
FROM scratch
ADD orchent /
ENTRYPOINT ["/orchent"]
CMD ["--help"]

**Comment by bwegh** [comment]
does your build instruction work on MacOs, Marcia or are you building on another system?

**Comment by bwegh** [comment]
the issue with the docker is that there is no Ca-file installed on the Docker, so orchent does not know which CAs to trust.

**Comment by maricaantonacci** [comment]
The docker image was built when the orchestrator was not exposing https endpoint. 
Build instruction tested on Ubuntu

**Comment by bwegh** [comment]
Hi @maricaantonacci , @gmolto 
I just added a feature to specify the CA File which should help fixing this issue
see https://github.com/indigo-dc/orchent/pull/15 and https://github.com/indigo-dc/orchent/releases/tag/0.4.0

**Comment by bwegh** [comment]
@gmolto, @maricaantonacci 
could you please test if this image works for you:
https://github.com/indigo-dc/orchent/releases/download/0.4.0/orchent_container_0.4.0.tgz

**Comment by gmolto** [comment]
docker import orchent_container_0.4.0.tgz orchent
docker run orchent depls
container_linux.go:247: starting container process caused "exec: \"depls\": executable file not found in $PATH"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"depls\": executable file not found in $PATH".
ERRO[0001] error getting events from daemon: net/http: request canceled

Am I missing something?

**Comment by bwegh** [comment]
I get the same error
```
$ docker run orchent:0.4.0
standard_init_linux.go:178: exec user process caused "no such file or directory"
```
@maricaantonacci do you know what is missing or what I am doing wrong?
I aslo tried by changing the build but that did not help either ... can you maybe help here.

**Comment by maricaantonacci** [comment]
I have just created a new docker image (marica/orchent:0.4.0) from https://github.com/indigo-dc/orchent/archive/0.4.0.tar.gz just modifying the build command in utils/compile.sh as explained before...and it works correctly.
How did you create the image? Are you following the same path?

**Comment by bwegh** [comment]
It seems like I am doing something wrong ... please have a look at the [docker branch](https://github.com/indigo-dc/orchent/blob/docker/utils/build_docker.sh#L34) it does not build the orchent binary ...
I assume some parameter to `isntallsuffix` is missing.

**Comment by maricaantonacci** [comment]
Bas, 
I think that it's a problem of paths..can you try with 
CGO_ENABLED=0 GOOS=linux go build -o $ORCHENT -a -installsuffix -v ${GOPATH}/orchent.go 
at [L34](https://github.com/indigo-dc/orchent/blob/docker/utils/build_docker.sh#L34)

**Comment by bwegh** [comment]
@gmolto , @maricaantonacci 
could you please check the [docker image]( https://github.com/indigo-dc/orchent/releases/download/0.4.0/orchent_container_0.4.0.tgz) that I uploaded?
At least for me it is working now.

@maricaantonacci :
it was a path issue, which was caused by not using the `$ORCHENT` variable. Thanks.

**Comment by alberto-brigandi** [comment]
Hi @bwegh,
wouldn't it be possible the add the `ca-certificates.crt` file (taken from an updated linux distro) directly in the docker image as default?

**Comment by bwegh** [comment]
added it to the branch (only working on debian based systems), are you able to test it @alberto-brigandi ?
I have very little time today

**Comment by alberto-brigandi** [comment]
>added it to the branch

do you mean the `ca-certificates.crt` file logic? Because I don't see it

**Comment by bwegh** [comment]
there is already a logic from go, added just the ca-certificates.crt file to the default location
see [here](https://github.com/indigo-dc/orchent/blob/docker/utils/Dockerfile#L3)
was missing before, sorry

**Comment by bwegh** [comment]
I jsut tested it and it works for me.
@gmolto , @maricaantonacci , @alberto-brigandi  
could you please also all test it and confirm if it is working, thanks.

the [docker-image](https://github.com/indigo-dc/orchent/releases/download/0.4.0/orchent_container_0.4.0.tgz) in the release is  updatede

**Comment by gmolto** [comment]
Hi,

Thank you for the effort. I am facing some troubles:

Steps to reproduce:

**wget --no-check-certificate https://github.com/indigo-dc/orchent/releases/download/0.4.0/orchent_container_0.4.0.tgz**
**docker import orchent_container_0.4.0.tgz orchent**
**docker run orchent depls**
container_linux.go:247: starting container process caused "exec: \"depls\": executable file not found in $PATH"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"depls\": executable file not found in $PATH".
ERRO[0001] error getting events from daemon: net/http: request canceled

**docker run orchent orchent depls**
container_linux.go:247: starting container process caused "exec: \"orchent\": executable file not found in $PATH"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"orchent\": executable file not found in $PATH".
ERRO[0001] error getting events from daemon: net/http: request canceled

¿How are you running the container?

**Comment by bwegh** [comment]
I am running it as you expected first:
```
docker run orchent depls
```
I have the same issue when purging the image and importing it ... so it seems the export is having issues.
Thanks a lot for your support. I will dig into it, any hints are very appreciated

**Comment by bwegh** [comment]
this works for me:
 - downloading [container](https://github.com/indigo-dc/orchent/releases/download/0.4.0/orchent_container_0.4.0.tar)
- running `docker load --input orchent_container_0.4.0.tar`
- executing `docker run orchent:0.4.0 --version`

what about you? @gmolto , @maricaantonacci , @alberto-brigandi 
does also SSL work for you?

**Comment by gmolto** [comment]
I can reproduce your behaviour but:

```
export ORCHENT_TOKEN=<IAM-TOKEN>
export ORCHENT_URL=https://orchestrator01-indigo.cloud.ba.infn.it
docker run -e ORCHENT_URL=$ORCHENT_URL -e ORCHENT_TOKEN=$ORCHENT_TOKEN orchent:0.4.0 depls
```
Yields the error:

retrieving deployment list:
error requesting list of providers:
 invalid character '<' looking for beginning of value

**Comment by bwegh** [comment]
just tested it on the command line ... looks like it is an issue with the orchestrator ...
@alberto-brigandi did you change something?

**Comment by alberto-brigandi** [comment]
Nope; I think that the problem is that
```
export ORCHENT_URL=https://orchestrator01-indigo.cloud.ba.infn.it
```
should be changed in
```
export ORCHENT_URL=https://orchestrator01-indigo.cloud.ba.infn.it/orchestrator/
```

**Comment by bwegh** [comment]
I just double checked:
```
export ORCHENT_TOKEN=<IAM TOKEN>
export ORCHENT_URL=https://orchestrator01-indigo.cloud.ba.infn.it/orchestrator/
docker run -e ORCHENT_URL=$ORCHENT_URL -e ORCHENT_TOKEN=$ORCHENT_TOKEN 
```
returns the same as
```
orchent:0.4.0 depls
```

so for me the docker issue including SSL is fixed
