### ISSUE TITLE
add filter for deployment list

### ISSUE THREAD

**Issue by bwegh** [indigo-dc/orchent#24]
- [x] only owned by the user
- [ ] by date/time

**Comment by alberto-brigandi** [comment]
Hi @bwegh,
regarding the first point, with https://github.com/indigo-dc/orchestrator/commit/5bc8d5c3d2358183fe008a7d01fb974953ca809e I've added a native way to filter the deployments on owner basis.
You can find the documentation [here](https://indigo-dc.github.io/orchestrator/restdocs/#_request_parameters)

**Comment by bwegh** [comment]
thanks @alberto-brigandi 
is implemented in master
