### ISSUE TITLE
Not urgent: Simplify the commandline

### ISSUE THREAD

**Issue by iblanque** [indigo-dc/orchent#6]
Hi,

A very simple (and convenient) improvement could be to have the capability of specifying the Orchestrator as an environment variable or even better as an entry in a file. This will simplify the command line structure.

**Comment by bwegh** [comment]
thanks for the input and sorry for the late reply, somehow I must have missed the notification for it.
Yes I will address that and will add as a first step environmental variable for it

**Comment by bwegh** [comment]
which version of orchent are you using? 0.1 I assume, so the offical released version?
or have you tried [0.2](https://github.com/indigo-dc/orchent/releases/tag/v0.2.0).
This is exactly what you meant, the ORCHENT_URL, or did I misunderstand?

**Comment by bwegh** [comment]
assuming this is done, if not please reopen and explain what is missing
